name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 3.x.x
        
    - name: Restore dependencies
      run: dotnet restore ProductOrderApp/ProductOrderApp.sln

      
    - name: Build (Release)
      run: dotnet build ProductOrderApp/ProductOrderApp.csproj --configuration Release --no-restore
      
    - name: Test (Release)
      run: dotnet test --configuration Release --no-build --no-restore

    - name: Pack (Release)
      run: dotnet pack --configuration Release --output .\nuget --no-build --no-restore

    - name: Publish
      if: github.event_name == 'workflow_dispatch' # manually run
      run: |
          if ( "${{github.ref}}" -match "^refs/tags/[0-9]+\.[0-9]+\.[0-9]+$" ) {
              dotnet nuget push .\nuget\*.nupkg -s nuget.org -k ${{secrets.NUGET_TOKEN}} --skip-duplicate
          } else {
              echo "publish is only enabled by tagging with a release tag"
          }